stages:
- build
- test

build:
  stage: build
  script:
    - cd RestaurantApplicationBackend
    - ./gradlew build -x test
    - ./gradlew.bat --stop

test:
  stage: test
  script:
    - cd RestaurantApplicationBackend
    - ./gradlew test
    - ./gradlew.bat --stop

after_script:
  - echo "DA"
  - exit